---
name: virtme-ng build

"on":
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * *"

permissions:
  contents: read

jobs:
  vng-tests:
    uses: ralflici/ovpn-kmod-ci/.github/workflows/vng-matrix.yml@test-new-vng
    with:
      ci-repository: ralflici/ovpn-kmod-ci
      cache-prefix: ovpn-dco
      guest-script: ci/run-build.sh
    secrets: inherit
